name: Tests and Checks

on: pull_request

jobs:
  tests:
    name: App tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        env:
          POETRY_VERSION: 1.1.13

      - name: Install dependencies
        run: |
          poetry install

      - name: Test with pytest
        run: |
          poetry run pytest tests

  python:
    uses: lidofinance/linters/.github/workflows/python.yml@master
    with:
      dirs: myproject tests # TODO don't forget rename this
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master
